language: node_js
os: osx
sudo: enabled
env:
  - SPLASH_TOKEN=d780e2d296ea4a26b9a373cfd3265f8f949de7260d62f7dc838d5396142cd3a6
before_install:
  - "yarn global add babel-cli"
node_js:
  - "9"
  - "8"
